language: csharp
mono: none
dotnet: 2.1.3
dist: trusty
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
    - PGPORT=5433
install:
  - dotnet restore
before_script:
  - sudo -U postgres psql -c 'ALTER USER postgres WITH PASSWORD 'password';'
  - sudo -U postgres psql -c 'create database postgres;'
script:
  - dotnet build
  - find test/ -maxdepth 4 -name "*Tests.csproj" -type f -print0 | xargs -0 -L1 dotnet test --no-build
...
