language: csharp
mono: none
dotnet: 2.1.3
dist: trusty
install:
  - dotnet restore
script:
  - dotnet build
  - find test/ -maxdepth 4 -name "*Tests.csproj" -type f -print0 | xargs -0 -L1 dotnet test --no-build
...
