## Config for the Redis in-memory database instance.
## This file should be shared among all services.

redis:
  host: localhost  ## Hostname.
  port: 6379  ## Port number. Default 6379.
  db: 0  ## Database number 0 to 15.

  ## Additional configuration. These values are passed directly to Redis.
  ## See https://stackexchange.github.io/StackExchange.Redis/Configuration.html
  ## for a full list
  # extra: abortConnect=false
