## Options common to all microservices.
## The file is intended to be shared among all the services

## Config for the service runner.
service:
  ## The pub/sub implementation to use. One of redis (recommended),
  ## dummy (default). The dummy pub/sub doesn't work across services and is
  ## intended for testing only.
  pubSub: redis


## Config for the RESTful web server. See the per-service template for
## more options.
restful:
  ## Password to authenticate services. Change it from the default to a
  ## long string or comment it out to disable.
  localAuthenticationPassword: password


## Config for the Redis in-memory database instance.
redis:
  host: localhost  ## Hostname.
  port: 6379  ## Port number. Default 6379.
  db: 0  ## Database number 0 to 15.

  ## Additional configuration. These values are passed directly to Redis.
  ## See https://stackexchange.github.io/StackExchange.Redis/Configuration.html
  ## for a full list
  # extra: abortConnect=false,connectRetry=99


## Config to allow each service to communiate to each other
serviceAssignment:
  ## Static mapping uses fixed IP addresses and port numbers. The key
  ## is the service name and then value is the host/port assignment
  static:
    parrot: {host: localhost, port: 5100}
