name: deploy

on: [ workflow_dispatch ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: TPP.Core

    steps:
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - uses: actions/checkout@v2
      - name: Publish the core
        run: dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true --no-self-contained
      - name: Deploy the core to TPP
        env:
          SSHUSER: ${{ secrets.TPP_SSH_USER }}
          SSHPRIVKEY: ${{ secrets.TPP_SSH_PRIVATE_KEY }}
          SSHHOST: ${{ secrets.TPP_SSH_HOST }}
          SSHPORT: ${{ secrets.TPP_SSH_PORT }}
        run: |
          echo "$SSHPRIVKEY" > tpp.key
          chmod 600 tpp.key
          scp -q -i tpp.key -o StrictHostKeyChecking=no -P ${SSHPORT} bin/Release/net5.0/linux-x64/publish/TPP.Core ${SSHUSER}@${SSHHOST}:core_update
          ssh -q -i tpp.key -o StrictHostKeyChecking=no -p ${SSHPORT} ${SSHUSER}@${SSHHOST} 'mv core_update core && systemctl --user restart tpp-dualcore'
