name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.1.0
      with:
        mongodb-version: 4.2.3
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Test with dotnet
      run: dotnet test
    - name: Regenerate core config json schema
      run: |
        cd Core
        dotnet run -- regenjsonschema
        git add config.schema.json
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "update core config json schema"
        cd ..
    - name: Push changed core config json schema
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
