name: regen-json-schema

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - uses: actions/checkout@v2
      - name: Regenerate core config json schemas
        run: |
          cd Core
          dotnet run -- regenjsonschemas
          git add config.schema.json
          git add config.runmode.schema.json
          git add config.matchmode.schema.json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff-index --quiet HEAD || git commit -m "update core config json schemas"
          git pull --rebase
          cd ..
      - name: Push changed core config json schemas
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
