name: test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-rc.1.20452.10
      - uses: actions/checkout@v2
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2.3
          mongodb-replica-set: rs0
      - name: Test with dotnet
        run: dotnet test
